### ISSUE TITLE
Binary releases

### ISSUE THREAD

**Issue by dumblob** [ttsiodras/rsbep-backup#1]
I'm working with several operating systems and on unix-inspired ones, there is usually no issue with compiling and running anything, but on Windows this is getting really complicated.

This gets even harder due to the fact, that the Windows machines I'm working with are mostly from corporate environment where it's not easy install software any time.

Thus my question, whether you could release some binary version for Windows? Don't worry about the shell scripts - on all the Windows machines there was [Git for Windows](https://git-scm.com/download/win ) which is a maintained version of a minimal GNU (POSIX compatible) environment (I have a really good experience with exactly with this Git-bundled GNU env on Windows). The FUSE support might even already now work with [WinFsp](https://github.com/billziss-gh/winfsp ) or [Dokany](https://github.com/dokan-dev/dokany ).

There is also the option of using some container technology like docker as some of them already run on Windows without issues. Even though I think that the future lies within Windows Subsystem for Linux (the newest version significantly increased compatibility by incorporating the Linux kernel itself - think of [User-mode Linux](https://en.wikipedia.org/wiki/User-mode_Linux )), so we might consider just WSL compatibility to make things simple.

**Comment by ttsiodras** [comment]
I fear that again I won't be able to help you... I have abandoned Windows since about two decades ago - and my programming life has significantly improved because of that choice. 

If however life became unusually cruel, and somehow forced me into working on Windows again... I would for sure try to build my rsbep under WSL, as you suggested - did you? A small search I did seems to indicate that WSL can compile and run pretty much everything user-mode-y (like rsbep) without an issue - and that the compiled binaries can, in fact, access the files inside Windows partitions. 

It seems this would address your concerns, no?

**Comment by dumblob** [comment]
>I would for sure try to build my rsbep under WSL, as you suggested - did you?

I didn't try with the newest "usermode Linux" WSL as I didn't have the opportunity :cry:. But with the older WSL (4 months old) I wasn't successful.

Anyway thanks for the update (better ask than rely on info from README which is several years old).
